version: "3.8"
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nest-docker-postgres    
    ports:
      - '3000:3000' 
      - '4000:4000' 
    volumes:
      - ./src:/app/src